export const USER_LOGIN = "USER_LOGIN";

export const DASHBOARD_DATA = "DASHBOARD_DATA";

export const PROJECT_DETAIL = "PROJECT_DETAIL";

export const TOOGLE_MENU = "TOOGLE_MENU";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const RESET_PASSWORD = "RESET_PASSWORD";

export const PROJECT_DETAIL_DATA = "PROJECT_DETAIL_DATA";

export const PROJECT_TEAM_DATA = "PROJECT_TEAM_DATA";

export const AUTH_KEY_SET = "AUTH_KEY_SET";

export const USER_PROFILE="USER_PROFILE";

export const INSTALLATION_DEVICE = "INSTALLATION_DEVICE";

export const DATA_ANALYSIS_PROJECT_LIST = "DATA_ANALYSIS_PROJECT_LIST";

export const DATA_ANALYSIS_PROJECT_LIST_SUB_MENU = "DATA_ANALYSIS_PROJECT_LIST_SUB_MENU";

export const PROJECT_ANALYSIS_DATA = "PROJECT_ANALYSIS_DATA";

export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";

export const SERVICE_REQUIREMENT = "SERVICE_REQUIREMENT";

export const PROJECT_ALERT_LIST = "PROJECT_ALERT_LIST";

export const DISPENSER_DATA = "DISPENSER_DATA";