export const USER_LOGIN = "USER_LOGIN";

export const DASHBOARD_DATA = "DASHBOARD_DATA";

export const PROJECT_DETAIL = "PROJECT_DETAIL";

export const TOOGLE_MENU = "TOOGLE_MENU";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

export const RESET_PASSWORD = "RESET_PASSWORD";

export const PROJECT_DETAIL_DATA = "PROJECT_DETAIL_DATA";

export const PROJECT_TEAM_DATA = "PROJECT_TEAM_DATA";

export const AUTH_KEY_SET = "AUTH_KEY_SET";

export const USER_PROFILE="USER_PROFILE";

export const INSTALLATION_DEVICE = "INSTALLATION_DEVICE";

export const DATA_ANALYSIS_INSTALLATION_LIST = "DATA_ANALYSIS_INSTALLATION_LIST";

export const DATA_ANALYSIS_PROJECT_LIST_SUB_MENU = "DATA_ANALYSIS_PROJECT_LIST_SUB_MENU";

export const PROJECT_ANALYSIS_DATA = "PROJECT_ANALYSIS_DATA";

export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";

export const SERVICE_REQUIREMENT = "SERVICE_REQUIREMENT";

export const PROJECT_ALERT_LIST = "PROJECT_ALERT_LIST";

export const DISPENSER_DATA = "DISPENSER_DATA";

export const DATA_ANALYSIS_MENU_LIST = "DATA_ANALYSIS_MENU_LIST";

export const PROJECT_TEAM_ASSO_DATA = "PROJECT_TEAM_ASSO_DATA";

export const CLEAR_REDUCER = "CLEAR_REDUCER";

export const PROJECT_SELECTED = "PROJECT_SELECTED";

export const PROJECT_LIST = "PROJECT_LIST";

export const HEALTH_STATUS = "HEALTH_STATUS";

export const HEALTH_LOCATION_STATUS = "HEALTH_LOCATION_STATUS";

export const REPORT_SERVICE_LIST = "REPORT_SERVICE_LIST";

export const REPORTS_LIST = "REPORTS_LIST";

export const MODAL_PROJECT_ANALYSIS_DATA = "MODAL_PROJECT_ANALYSIS_DATA";

export const PARTNER_THEME = "PARTNER_THEME";

export const PAGE_LOADING = "PAGE_LOADING";

export const ADMIN_PROJECT_CREATE = "ADMIN_PROJECT_CREATE";

export const ADMIN_PROJECT_LOCATION_CREATE = "ADMIN_PROJECT_LOCATION_CREATE";

export const ADMIN_PROJECT_UPDATE = "ADMIN_PROJECT_UPDATE";

export const ADMIN_PROJECT_LIST = "ADMIN_PROJECT_LIST";

export const PROJECT_METRIC_LIST = "PROJECT_METRIC_LIST";

export const PROJECT_ANALYSIS_INITIALISE = "PROJECT_ANALYSIS_INITIALISE";

export const PROJECT_METRIC_INITIALISE = "PROJECT_METRIC_INITIALISE";

export const PROJECT_USER_CREATE = "PROJECT_USER_CREATE";

export const PROJECT_IFRAME = "PROJECT_IFRAME";

export const INSTALLATION_DEVICE_UPDATE = "INSTALLATION_DEVICE_UPDATE";

export const USER_SEARCH = "USER_SEARCH";

export const PROJECT_TEAM_MEMBER_INITIALISE = "PROJECT_TEAM_MEMBER_INITIALISE";

export const PROJECT_TEAM_ASSOCIATION_INITIALISE = "PROJECT_TEAM_ASSOCIATION_INITIALISE";

export const PROJECT_DATA_INITIALISE = "PROJECT_DATA_INITIALISE";

export const ALERT_DATA_INITIALISE = "ALERT_DATA_INITIALISE";

export const PROJECT_LOCATION_INITIALISE = "PROJECT_LOCATION_INITIALISE";

export const INSTALLATION_INITIALISE = "INSTALLATION_INITIALISE";

export const HEALTH_INITIALISE = "HEALTH_INITIALISE";

export const INSTALLATION_LIST_INITIALISE = "INSTALLATION_LIST_INITIALISE";

export const HEALTH_STATUS_INITIALISE = "HEALTH_STATUS_INITIALISE";

